# Generated by Django 5.1.3 on 2024-12-08 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hasaki', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackDetail',
            fields=[
                ('detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback_id', models.IntegerField(null=True)),
                ('reply_content', models.TextField()),
                ('reply_time', models.DateTimeField()),
                ('reply_to_customer', models.IntegerField(default=1)),
            ],
        ),
    ]
