# Generated by Django 5.1.3 on 2024-11-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpaHasaki', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='employee',
        ),
        migrations.AddField(
            model_name='feedback',
            name='employee_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='workshifts',
            name='shifts_date',
            field=models.DateField(),
        ),
    ]
